[workspace]
resolver = "3"
members = ["ion_common", "ion_engine", "ion_engine/derive_engine", "ion_game", "ion_host"]

[profile.test]
opt-level = 3

[profile.dev]
[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true