[package]
name = "ion_host"
version = "0.1.0"
edition = "2024"
license = "All Rights Reserved"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ion_common = { path = "../ion_common", features = ["log_dbg"] }
